config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
get '/admin/pages/new', to: 'pages#new', as: :new
post 'admin/pages/:id', to: 'pages#create'
get '/admin/pages/:id/edit', to: 'pages#edit', as: :page
patch '/admin/pages/:id', to: 'pages#update'

post "/admin/pages/:id/rows/new" , to: "rows#create", as: :create_row
get "/admin/rows/:id/edit" , to: "rows#edit", as: :edit_row
post "/admin/rows/:id/edit" , to: "rows#update", as: :update_row
delete "/admin/rows/:id" , to: "rows#destroy", as: :delete_row


get "/admin/columns/:id/edit" , to: "columns#edit", as: :edit_column
delete "/admin/columns/:id" , to: "columns#destroy", as: :delete_column

get "/admin/rows/:id/columns/new" , to: "columns#new", as: :new_column
post "/admin/rows/:id/columns/new" , to: "columns#create", as: :create_column

delete "/admin/pages/:id" , to: "pages#destroy", as: :delete_page
#get "/admin/pages/:id/rows/:row_id/columns/new", to: "columns#new", as: :new_column
#post "/admin/pages/:id/rows/:row_id/columns/new", to: "columns#create", as: :create_column

#delete "/admin/columns/:id" , to: "column#destroy", as: :delete_column

scope '/admin' do
	resources :pages, except: [:show , :update] do
		resources :rows, except: [:create, :destroy] do
			resources :columns, except: [:create]
		end
		
	end
end
  
  root 'pages#index'

  get '/:slug', to: 'pages#show', as: :show

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/column.rb
class Column < ApplicationRecord
  belongs_to :row

  include RailsSortable::Model
  set_sortable :order 
end

app/models/page.rb
class Page < ApplicationRecord

	has_many :rows, dependent: :destroy
	validates :slug, presence: true

	accepts_nested_attributes_for :rows
	
end

app/models/row.rb
class Row < ApplicationRecord
  belongs_to :page
  has_many :columns, dependent: :destroy

  include RailsSortable::Model
  set_sortable :order 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController



	def new
		
		@row = Row.find(params[:id])
		@column = Column.new
	end

  def create
    #@page = Page.find_by(params[:page_id])
	
	@row = Row.find(params[:id])
	@column = @row.columns.create(column_params)
	#@column.create("row_id" => "c_type_#{@row.id}")
	#@column = Column.new(column_params)
	#@row.columns.create(column_params)

	#@column = Column.new( row_id: @row.id )
	if @column.save!
		respond_to do |f|
	    f.html { redirect_to edit_page_path(@column.row.page_id) }
	    f.js
		end
	end

  end
 
  
  def show
  	@row = Row.find(params[:id])
  end

  def destroy
  	
  	@column = Column.find(params[:id])
  	@column.destroy

  	    respond_to do |f|
    f.html { redirect_to edit_page_path(@column.row.page_id) }
    f.js
	end

  end

  private
    def column_params
      params.require(:columns).permit(:order,									
      								:text_color,
									:background_color,
									:text_align,
									:vertical_align,
									:size_mobile,
									:tablet_size,
									:desktop_size,
									:smarttv_size,
									:hide_mobile,
									:hide_tablet,
									:hide_desktop,
									:row_id
									)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index
    @pages = Page.all
  end

  def new
    @page = Page.new
  end

  def show
    @page = Page.includes(rows: [:columns]).find_by(slug: params[:slug])
    @rows = @page.rows.order(:order).all
  end

  def create
    @page = Page.new(page_params)
    
    if @page.save
      redirect_to edit_page_path(@page)
    else
      render 'new'
    end
  end

  def edit
    @page = Page.find(params[:id])
  end


  def update
    @page = Page.find(params[:id])
 
    if @page.update(page_params)
      redirect_to @page
    else
      render 'edit'
    end
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy
   
    redirect_to :action => 'index'
  end

  private
  def page_params
    params.require(:page).permit(:title, :description, :slug, :follow, :index)
  end


end

app/controllers/rows_controller.rb
class RowsController < ApplicationController
  before_action :set_row, only: [:edit, :update, :show, :destroy]
  
	def new
		@row = Row.new
	end

  def create
    @page = Page.find(params[:id])
    rows_count = @page.rows.count + 1
    @row = Row.new(order: rows_count, html_class: 'white',  page_id: @page.id )
    @row.save!
    
    respond_to do |format|
    format.html { redirect_to edit_page_path(@row.page_id) }
    format.js
    end
  end

  def show ; end
  def edit ; end

  def update
  @row.update(row_params)

  respond_to do |format|
    format.html { redirect_to edit_page_path(@row.page_id) }
    format.js
    end
  end

  def destroy
  	@row.destroy

    respond_to do |format|
      format.html { redirect_to edit_page_path(@row.page_id) }
      format.js
	  end
  end

  private

  def set_row
    @row = Row.find(params[:id])
  end

  def row_params
    params.require(:rows).permit( :order, :html_class, :page_id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/helpers/pages_helper.rb
module PagesHelper

  def title(page_title)
    content_for :title, page_title.to_s
  end

  def description(page_description)
    content_for :description, page_description.to_s
  end

  def index_follow(page_index, page_follow)
    page_index == true ? page_index ="INDEX" : page_index = "NOINDEX"
    page_follow == true ? page_follow ="FOLLOW" : page_follow = "NOFOLLOW"
    content_for :index_follow, (page_index.to_s + ', ' + page_follow.to_s)
  end

  def follow(page_follow)
    content_for :follow, page_follow.to_s
  end

end

app/helpers/rows_helper.rb
module RowsHelper
end

app/views/columns/_column.html.erb
<div class="col <%= column.background_color  %>">Kolumna<%= column.id %>
	
<br>
	
</div>

 

app/views/columns/_form.html.erb
<div id="new_column" class="">
<div class="col s12 blue-grey darken-2 white-text text-lighten-1">Nowa kolumna</div>

<%= form_for :columns, data: {remote: true} do |f| %>

 <p>
      <input type="checkbox" id="test6" checked="checked" />
      <label for="test6">Yellow</label>
    </p>

    <!-- Switch -->
  


<div class="">
	<div class="input-field col m6 l3">
		

  <p>  
    <%= f.label :order %><br>
    <%= f.hidden_field :order %>
  </p>
  
  <p>  
    <% f.label :row_id %><br>
    <%= f.text_field :row_id %>
  </p>

    <%= f.label :background_color %><br>
    <%= f.text_field :background_color %>

	
<div class="palette-container">
	<table >
<tr class="palette_tr"><td class="palette red lighten-5"></td><td class="palette pink lighten-5"></td><td class="palette purple lighten-5"></td><td class="palette deep-purple  lighten-5"></td><td class="palette indigo lighten-5"></td><td class="palette blue lighten-5"></td><td class="palette light-blue lighten-5"></td><td class="palette cyan lighten-5"></td></tr>
<tr class="palette_tr"><td class="palette red lighten-4"></td><td class="palette pink lighten-4"></td><td class="palette purple lighten-4"></td><td class="palette deep-purple  lighten-4"></td><td class="palette indigo lighten-4"></td><td class="palette blue lighten-4"></td><td class="palette light-blue lighten-4"></td><td class="palette cyan lighten-4"></td></tr>
<tr class="palette_tr"><td class="palette red lighten-3"></td><td class="palette pink lighten-3"></td><td class="palette purple lighten-3"></td><td class="palette deep-purple  lighten-3"></td><td class="palette indigo lighten-3"></td><td class="palette blue lighten-3"></td><td class="palette light-blue lighten-3"></td><td class="palette cyan lighten-3"></td></tr>
<tr class="palette_tr"><td class="palette red lighten-2"></td><td class="palette pink lighten-2"></td><td class="palette purple lighten-2"></td><td class="palette deep-purple  lighten-2"></td><td class="palette indigo lighten-2"></td><td class="palette blue lighten-2"></td><td class="palette light-blue lighten-2"></td><td class="palette cyan lighten-2"></td></tr>
<tr class="palette_tr"><td class="palette red lighten-1"></td><td class="palette pink lighten-1"></td><td class="palette purple lighten-1"></td><td class="palette deep-purple  lighten-1"></td><td class="palette indigo lighten-1"></td><td class="palette blue lighten-1"></td><td class="palette light-blue lighten-1"></td><td class="palette cyan lighten-1"></td></tr>
<tr class="palette_tr"><td class="palette red "></td><td class="palette pink "></td><td class="palette purple "></td><td class="palette deep-purple  "></td><td class="palette indigo "></td><td class="palette blue "></td><td class="palette light-blue "></td><td class="palette cyan "></td></tr>
<tr class="palette_tr"><td class="palette red darken-1"></td><td class="palette pink darken-1"></td><td class="palette purple darken-1"></td><td class="palette deep-purple  darken-1"></td><td class="palette indigo darken-1"></td><td class="palette blue darken-1"></td><td class="palette light-blue darken-1"></td><td class="palette cyan darken-1"></td></tr>
<tr class="palette_tr"><td class="palette red darken-2"></td><td class="palette pink darken-2"></td><td class="palette purple darken-2"></td><td class="palette deep-purple  darken-2"></td><td class="palette indigo darken-2"></td><td class="palette blue darken-2"></td><td class="palette light-blue darken-2"></td><td class="palette cyan darken-2"></td></tr>
<tr class="palette_tr"><td class="palette red darken-3"></td><td class="palette pink darken-3"></td><td class="palette purple darken-3"></td><td class="palette deep-purple  darken-3"></td><td class="palette indigo darken-3"></td><td class="palette blue darken-3"></td><td class="palette light-blue darken-3"></td><td class="palette cyan darken-3"></td></tr>
<tr class="palette_tr"><td class="palette red darken-4"></td><td class="palette pink darken-4"></td><td class="palette purple darken-4"></td><td class="palette deep-purple  darken-4"></td><td class="palette indigo darken-4"></td><td class="palette blue darken-4"></td><td class="palette light-blue darken-4"></td><td class="palette cyan darken-4"></td></tr>
<tr class="palette_tr"><td class="palette red accent-1"></td><td class="palette pink accent-1"></td><td class="palette purple accent-1"></td><td class="palette deep-purple  accent-1"></td><td class="palette indigo accent-1"></td><td class="palette blue accent-1"></td><td class="palette light-blue accent-1"></td><td class="palette cyan accent-1"></td></tr>
<tr class="palette_tr"><td class="palette red accent-2"></td><td class="palette pink accent-2"></td><td class="palette purple accent-2"></td><td class="palette deep-purple  accent-2"></td><td class="palette indigo accent-2"></td><td class="palette blue accent-2"></td><td class="palette light-blue accent-2"></td><td class="palette cyan accent-2"></td></tr>
<tr class="palette_tr"><td class="palette red accent-3"></td><td class="palette pink accent-3"></td><td class="palette purple accent-3"></td><td class="palette deep-purple  accent-3"></td><td class="palette indigo accent-3"></td><td class="palette blue accent-3"></td><td class="palette light-blue accent-3"></td><td class="palette cyan accent-3"></td></tr>
<tr class="palette_tr"><td class="palette red accent-4"></td><td class="palette pink accent-4"></td><td class="palette purple accent-4"></td><td class="palette deep-purple  accent-4"></td><td class="palette indigo accent-4"></td><td class="palette blue accent-4"></td><td class="palette light-blue accent-4"></td><td class="palette cyan accent-4"></td></tr>
</table>
</div>
<div style='overflow-x:scroll;overflow-y:hidden;width:250px;height:200px'>
    <div style='width:400px;height:250px'></div>
</div>


	 <!-- Switch -->
  <div class="switch">
    <label>
      Off
      <input type="checkbox">
      <span class="lever"></span>
      On
    </label>
  </div>

  <p>
      <input type="checkbox" id="test5" />
      <label for="test5">Red</label>
    </p>
	</div>
	<div class=" col m6 l5">
   
 

 </span>
    <a class=" tooltipped" data-position="bottom" data-delay="50" data-tooltip="Linijka"><div>
      <div class="col s1 blue-grey darken-2 white-text text-lighten-1">1</div>
      <div class="col s1 blue-grey  white-text text-lighten-1">2</div>
      <div class="col s1 blue-grey darken-2 white-text text-lighten-1">3</div>
      <div class="col s1 blue-grey  white-text text-lighten-1">4</div>
      <div class="col s1 blue-grey darken-2 white-text text-lighten-1">5</div>
      <div class="col s1 blue-grey  white-text text-lighten-1">6</div>
      <div class="col s1 blue-grey darken-2 white-text text-lighten-1">7</div>
      <div class="col s1 blue-grey  white-text text-lighten-1">8</div>
      <div class="col s1 blue-grey darken-2 white-text text-lighten-1">9</div>
      <div class="col s1 blue-grey  white-text text-lighten-1">10</div>
      <div class="col s1 blue-grey darken-2 white-text text-lighten-1">11</div>
      <div class="col s1 blue-grey  white-text text-lighten-1">12</div>
  </div></a><br>
    <div class="switch">
    <label>
      <i class="material-icons right-align">visibility_off</i>
      <input type="checkbox">
      <span class="lever"></span>
     <i class="material-icons left-align">visibility</i>
    </label>
  </div>
    <p class="range-field">
    
      <span class="blue-grey-text text-darken-3"><i class="material-icons left">phone_iphone</i> Szerokość kolumny na smarphonach</span>
      <%= f.range_field :size_mobile, :min=>1, :max=>12, :value => 12, :class=>"slide", :id=>"size_mobile"%>
    </p>

     <p class="range-field">
     	<span class="blue-grey-text text-darken-3"><i class="material-icons left">tablet</i> Szerokość kolumny na tabletach</span>
      <%= f.range_field :tablet_size, :min=>1, :max=>12, :value => 12, :class=>"slide", :id=>"tablet_size"%>
      
    </p>

    <p class="range-field">
      
      <span class="blue-grey-text text-darken-3"><i class="material-icons left">computer</i> Szerokość kolumny na desktopach i laptopach</span>
      <%= f.range_field :desktop_size, :min=>1, :max=>12, :value => 12, :class=>"slide", :id=>"desktop_size"%>
    </p>
     <p class="range-field">
      <span class="blue-grey-text text-darken-3"><i class="material-icons left">personal_video</i> Szerokość kolumny na dużych monitorach</span>
      <%= f.range_field :smarttv_size, :min=>1, :max=>12, :value => 12, :class=>"slide", :id=>"smarttv_size"%>
    </p>


    <a class=" tooltipped" data-position="bottom" data-delay="50" data-tooltip="Linijka"><div>
      <div class="col s1 blue-grey darken-2 white-text text-lighten-1">1</div>
      <div class="col s1 blue-grey  white-text text-lighten-1">2</div>
      <div class="col s1 blue-grey darken-2 white-text text-lighten-1">3</div>
      <div class="col s1 blue-grey  white-text text-lighten-1">4</div>
      <div class="col s1 blue-grey darken-2 white-text text-lighten-1">5</div>
      <div class="col s1 blue-grey  white-text text-lighten-1">6</div>
      <div class="col s1 blue-grey darken-2 white-text text-lighten-1">7</div>
      <div class="col s1 blue-grey  white-text text-lighten-1">8</div>
      <div class="col s1 blue-grey darken-2 white-text text-lighten-1">9</div>
      <div class="col s1 blue-grey  white-text text-lighten-1">10</div>
      <div class="col s1 blue-grey darken-2 white-text text-lighten-1">11</div>
      <div class="col s1 blue-grey  white-text text-lighten-1">12</div>
  </div></a>
    
</div>


    	<%f.select :thc, options_for_select((10..100).step(10).to_a.map{|s| ["#{s}%", s]})%>


 <div class="input-field col s12">
    <%= f.submit 'Zapisz kolumnę', class: "waves-effect waves-light btn blue-grey darken-4" %>
  </div>
</div>
<% end %>
</div>

app/views/columns/create.js.erb
$('#new_column').remove();
$('tr#Row_<%=@row.id%>').find('#new_link_column_row').show();
$('tr#Row_<%=@row.id%>').find('.added_columns').append('<div class="col s6 <%= @column.background_color  %>">Kolumna<%= @column.id %><br></div>');



///$('#zero_rows').remove();
//$('#new_rows').show().removeClass('pulse');

app/views/columns/new.js.erb
$('tr#Row_<%=@row.id%>').find('#new_link_column_row').hide()
//$('tr#Row_<%=@row.id%>').replaceWith('<%= j render("form") %>');
$('tr#Row_<%=@row.id%>').find('.added_columns').append('<%= j render("form") %>');

app/views/pages/_form.html.erb
<div class="grey lighten-3">
<%= form_for @page,  url: { action: "update"} do |form| %>
  <%= @page.errors.full_messages.first if @page.errors.any? %>

  <div class="input-field col s9">
    <%= form.label :Tytuł_strony %><br>
    <%= form.text_field :title %>
  </div>
 
   <div class="input-field col s9">
    <%= form.label :Opis_strony %><br>
    <%= form.text_area :description , class: 'materialize-textarea'%>
  </div>

   <div class="input-field col s9">
    <%= form.label :URL %><br>
    <%= form.text_field :slug %>
  </div>

  
  <div class="switch">
    <label>
      Indeksuj w wyszukiwarce<br>
      Off
      <%= form.check_box(:index, :checked_value => "INDEX", :unchecked_value => "NOINDEX") %>
      
      <span class="lever"></span>
      On
    </label>
  </div>

  <div class="switch">
    <label>
      Podążaj (atrybut follow)<br>
      Off
      <%= form.check_box( :follow, :checked_value => 'FOLLOW', :unchecked_value => 'NOFOLLOW')%>
      
      <span class="lever"></span>
      On
    </label>
  </div>

<p>
    <%= form.submit 'Zapisz', class: "waves-effect waves-light btn blue-grey darken-4" %>
</p>
<% end %>



<div class="row ">

<table class="col s12 ">
  <tbody class="sortable" id="added_rows">  <!-- sortable target -->
    <% @page.rows.order(:order).all.each_with_sortable_id do |row, sortable_id| %>
      <tr class=" row z-depth-1 hoverable" style="display:block; min-height:100%; margin-bottom:15px;" id="<%= sortable_id %>">  <!-- Needs id tag on sorting elements -->
         <td class="padding0 center-align " style="display:block; min-width:100%; margin-bottom:15px;" >
          <div class="header handle blue-grey darken-4 blue-grey-text text-lighten-1 center-align " style="cursor:move;">Wiersz 
            <div class="right red-text" style="margin-right:10px;"><span class=" tooltipped" data-position="bottom" data-delay="50" data-tooltip="Usuń wiersz"><%= link_to delete_row_path(row.id), remote: true, method: :delete do %><span class="blue-grey-text text-lighten-1 "> <i class="material-icons">delete_forever</i></span ></span>


            <% end %><span class=" tooltipped" data-position="bottom" data-delay="50" data-tooltip="Edytuj wiersz"><%= link_to edit_row_path(row.id), remote: true do %><span class="blue-grey-text text-lighten-1"> <i class="material-icons">edit</i></span ><% end %></span></div></div>

          </div>
          <div class="body_row"><%= render row %>
            </div>


        </td>
    </tr>
    
  <% end %>
   </tbody>
  <tfoot>
       <tr class=" row z-depth-1" id="new-row">  <!-- Needs id tag on sorting elements -->
         <td class="" style="display:block; min-width:100%" >
          <div class="vertical-align blue-grey darken-4  z-depth-0 center-align dashed ">
            <% unless @page.rows.any? %>
            <div id="zero_rows">
                      Nie masz jeszcze żadnego wiersza.<br>
                      Dodaj pierwszy.

                      Wiersze ułatwiają układanie treści na stronie.<br>

              <%= link_to new_page_row_path(@page.id), id: "new_link", class: "btn-floating btn-large waves-effect waves-light blue-grey darken-4 pulse", remote: true do %>
              <i class="material-icons white-text">add</i>
            </div>
              <% end %>
            <% else %>
                 <div id="new_rows">     
              <% link_to new_page_row_path(@page.id), id: "new_link", class: "btn-floating btn-large waves-effect waves-light blue-grey darken-4 ", remote: true do %>
              <i class="material-icons white-text">add</i>
              <% end %>
              <span class=" tooltipped" data-position="bottom" data-delay="50" data-tooltip="Dodaj nowy wiersz"><%=  link_to create_row_path(@page.id), :method => :post , id: "new_link", class: "btn-floating btn-large waves-effect waves-light blue-grey lighten-1 ", remote: true do %>
              <i class="material-icons blue-grey-text text-darken-4">add</i>
            <% end %>
                </div></span>
            <% end %>
        
        </div>
        </td>
    </tr>
    </tfoot>
 
</table>

</div>

</div>

app/views/pages/edit.html.erb
Edytuj stronę
<%= render 'form' %>

app/views/pages/index.html.erb
<% title 'Strony' %>

<div class="row">
  <div class="col s12 m6 ">
    <h2 class="blue-grey-text text-darken-4">Strony (<%= @pages.count %>)</h2>
  </div>

  <div class="col s12 m6 ">
    <div style="font-size: 3.56rem;line-height: 110%;margin: 1.78rem 0 1.424rem 0;"><%= link_to  new_page_path, class: "blue-grey darken-4 blue-grey-text text-lighten-1 btn btn-large right" do %><i class="material-icons left">add</i> Dodaj nową stronę <% end %>
    </div>
  </div>


</row>

<% if @pages.any? %>

	
<table class="highlight ">
  <thead class="blue-grey-text text-darken-2">
    <tr>
      <td>Strona</td>
      <td class="action"><i class="material-icons">visibility</i></td>
      <td class="action"><i class="material-icons">edit</i></td>
      <td class="action"><i class="material-icons">delete_forever</i></td>
    </tr>
  </thead>
	<% @pages.each do |page| %>
		<tr>
      <td><%= link_to page.title, edit_page_path(page.id)  %></td>
      

      <td class="action"><%= link_to show_path(page.slug) do %><span class="blue-grey-text text-lighten-1 right"> <i class="material-icons">visibility</i></span ><% end %></td>
      <td class="action"><%= link_to edit_page_path(page.id) do %><span class="blue-grey-text text-lighten-1 right"> <i class="material-icons">edit</i></span ><% end %></td>

      <td class="action"><% link_to "Usuń", page, method: :delete, data: {confirm: "Potwierdź?"}  %> 
      <%= link_to delete_page_path(page.id), method: :delete, data: {confirm: "Potwierdź?"} do %><span class="blue-grey-text text-lighten-1 right "> <i class="material-icons">delete_forever</i></span ><% end %></td>
    </tr>
	<% end %>
</table>
<% else %>

	
	<div class="row">
	  <div class="col s12 ">
	    <div class="card">
	      
	      <div class="card-content vertical-align ">
	        <p><i class="material-icons orange-text text-darken-3 left">info</i>Nie masz jeszcze żadnej strony. <%= link_to 'Dodaj pierwszą stronę', new_page_path  %><a class="right btn-floating btn-large  waves-effect waves-light orange darken-3"><i class="material-icons right">add</i></a></p>
	        
	      </div>
	    </div>
	  </div>
	</div>
	          
	

<% end %>

app/views/rows/_row.html.erb
<div class="row <%= row.html_class %>">
	<% row.columns.any? %>

	<table class="col s12" style="display:block; ">
		

		<tbody class="added_columns row padding0" style="display:block;"><!-- sortable target -->
			<% row.columns.order(:order).all.each_with_sortable_id do |column, sortable_id_col| %>
				<tr class="column z-depth-1 hoverable padding0 col s<%=column.size_mobile%>" style="display:block; margin-bottom:15px; " id="<%= sortable_id_col %>">  <!-- Needs id tag on sorting elements -->
			         <td class="padding0 center-align " style="display:block; min-width:100%; margin-bottom:15px;" >
			          <div class="handle_column blue-grey darken-2 blue-grey-text text-lighten-4 center-align " style="cursor:move;">Kolumna 
			            <div class="right red-text" style="margin-right:10px;"><%= link_to delete_column_path(column.id), remote: true, method: :delete do %><a class=" tooltipped" data-position="bottom" data-delay="50" data-tooltip="Usuń kolumnę"><span class="blue-grey-text text-lighten-4 "> <i class="material-icons">delete_forever</i></span ></a>


			            <% end %><%= link_to edit_column_path(column.id), remote: true do %><span class=" tooltipped" data-position="bottom" data-delay="50" data-tooltip="Edytuj kolumnę"><span class="blue-grey-text text-lighten-4"> <i class="material-icons">edit</i></span ></span><% end %></div></div>

			          </div>
			          <div class="body_column "><%= render column %>
			            </div>


			        </td>
			    </tr>
				
			<% end %>
		</tbody> 
	</table>
<br><br><br>
	<span class=" tooltipped" data-position="bottom" data-delay="50" data-tooltip="Dodaj nową kolumnę">
	<%=  link_to new_column_path(row.id) , id: 'new_link_column_row', class: "btn-floating btn-large waves-effect waves-light blue-grey lighten-1 ", remote: true do %>
              <i class="material-icons blue-grey-text text-darken-4">add</i>
            <% end %>
    </span>
</div>

app/views/rows/create.js.erb
$('#new_row').remove();
$('#new_link').show();
$('#added_rows').append('<tr class=" row z-depth-1 hoverable" style="display:block; min-height:100%; margin-bottom:15px; " id="Row_<%=@row.id %>">         <td class="padding0 center-align " style="display:block; min-width:100%; margin-bottom:5px;" >          <div class=" handle blue-grey darken-4 blue-grey-text text-lighten-1 center-align " style="cursor:move;">Wiersz             <div class="right red-text" style="margin-right:10px;"><%= link_to delete_row_path(@row.id), remote: true, method: :delete do %><span class="blue-grey-text text-lighten-1 "> <i class="material-icons">delete_forever</i></span >            <% end %><%= link_to edit_row_path(@row.id), remote: true do %><span class="blue-grey-text text-lighten-1"> <i class="material-icons">edit</i></span ><% end %></div></div></div>          <div class="body_row"><%= j render(@row) %></div>        </td>    </tr>')
$('tr#Row_<%=@row.id%>').hide();
$('tr#Row_<%=@row.id%>').slideDown('slow');


///$('#zero_rows').remove();
//$('#new_rows').show().removeClass('pulse');

app/views/rows/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');

app/views/rows/update.js.erb
$('tr#Row_<%=@row.id%>').find('form').slideUp('slow');
$('#new_row').remove();
$('#new_link').show();
$('tr#Row_<%=@row.id%>').replaceWith('<tr class=" row z-depth-1 hoverable" style="display:block; min-height:100%; margin-bottom:5px;" id="Row_<%=@row.id %>">         <td class="padding0 center-align " style="display:block; min-width:100%; margin-bottom:5px;" >          <div class="handle blue-grey darken-4 blue-grey-text text-lighten-1 center-align " style="cursor:move;">Wiersz             <div class="right red-text" style="margin-right:10px;"><%= link_to delete_row_path(@row.id), remote: true, method: :delete do %><span class="blue-grey-text text-lighten-1 "> <i class="material-icons">delete_forever</i></span >            <% end %><%= link_to edit_row_path(@row.id), remote: true do %><span class="blue-grey-text text-lighten-1"> <i class="material-icons">edit</i></span ><% end %></div></div></div>          <div class="body_row"><%= j render(@row) %></div>        </td>    </tr>');


///$('#zero_rows').remove();
//$('#new_rows').show().removeClass('pulse');